version: '3'

networks:
  apilisa2:
    driver: bridge

services:
  database:
    image: mongo
    networks:
      - apilisa2
    environment:
      MONGOLAB_URI: ${DATABASE_URL:-}
    ports:
      - "27017:27017"
  
  app:
    image: node:16.13.0
    volumes:
      - '.:/backend/'
    working_dir: /backend/
    depends_on:
      - database
    networks:
      - apilisa2
    env_file:
      - .env
    ports:
      - 3333:3333
    command: npm run dev